import "./globals.css";
import Navbar from "./components/Navbar";
import { Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ["latin"] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <body className={rubik.className}>
       <Navbar />
       {children}
     </body>
    </html>
  )
}
